#pragma once

#ifndef WINCOPIES_UTIL_ENUM_ARITHMETIC_HPP
#define WINCOPIES_UTIL_ENUM_ARITHMETIC_HPP

#include "../../Kernel/Enum/Arithmetic.hxx"

#include "Operators.h"

BITWISE_ENUM_SHIFT_OPERATOR(+)
BITWISE_ENUM_SHIFT_OPERATOR2(+)

BITWISE_ENUM_SHIFT_ASSIGNMENT_OPERATOR(+, +=)
BITWISE_ENUM_SHIFT_ASSIGNMENT_OPERATOR2(+, +=)

ARITHMETIC_ENUM_INCREMENTATION_OPERATORS(++)

BITWISE_ENUM_SHIFT_OPERATOR(-)
BITWISE_ENUM_SHIFT_OPERATOR2(-)

BITWISE_ENUM_SHIFT_ASSIGNMENT_OPERATOR(-, -=)
BITWISE_ENUM_SHIFT_ASSIGNMENT_OPERATOR2(-, -=)

ARITHMETIC_ENUM_INCREMENTATION_OPERATORS(--)

BITWISE_ENUM_SHIFT_OPERATOR(*)
BITWISE_ENUM_SHIFT_OPERATOR2(*)

BITWISE_ENUM_SHIFT_ASSIGNMENT_OPERATOR(*, *=)
BITWISE_ENUM_SHIFT_ASSIGNMENT_OPERATOR2(*, *=)

BITWISE_ENUM_SHIFT_OPERATOR(/ )
BITWISE_ENUM_SHIFT_OPERATOR2(/ )

BITWISE_ENUM_SHIFT_ASSIGNMENT_OPERATOR(/ , /=)
BITWISE_ENUM_SHIFT_ASSIGNMENT_OPERATOR2(/ , /=)

BITWISE_ENUM_SHIFT_OPERATOR(%)
BITWISE_ENUM_SHIFT_OPERATOR2(%)

BITWISE_ENUM_SHIFT_ASSIGNMENT_OPERATOR(%, %=)
BITWISE_ENUM_SHIFT_ASSIGNMENT_OPERATOR2(%, %=)

#endif // WINCOPIES_UTIL_ENUM_ARITHMETIC_HPP