#pragma once

#ifndef WINCOPIES_TEMPLATES_CLASS_H
#define WINCOPIES_TEMPLATES_CLASS_H

#define CLASS_N(n) TEMPLATE_N(n, ) CLASS



#define SIGNED_CLASS(...) TEMPLATE_IF_SIGNED(__VA_ARGS__) CLASS
#define UNSIGNED_CLASS(...) TEMPLATE_IF_UNSIGNED(__VA_ARGS__) CLASS

#define INTEGRAL_CLASS(...) TEMPLATE_IF_INTEGRAL(__VA_ARGS__) CLASS
#define SIGNED_INTEGRAL_CLASS(...) TEMPLATE_IF_SIGNED_INTEGRAL(__VA_ARGS__) CLASS
#define UNSIGNED_INTEGRAL_CLASS(...) TEMPLATE_IF_UNSIGNED_INTEGRAL(__VA_ARGS__) CLASS

#define FLOAT_CLASS(...) TEMPLATE_IF_FLOAT(__VA_ARGS__) CLASS
#define ENUM_CLASS(...) TEMPLATE_IF_ENUM(__VA_ARGS__) CLASS

#endif WINCOPIES_TEMPLATES_CLASS_H