#pragma once

#ifndef WINCOPIES_TEMPLATES_INTERFACE_HXX
#define WINCOPIES_TEMPLATES_INTERFACE_HXX

#define SIGNED_INTERFACE(typeArray, ...) TEMPLATE_IF_SIGNED(ALL_BUT_FIRST_ARG typeArray) INTERFACE_CLASS(FIRST_ARG typeArray, __VA_ARGS__)
#define UNSIGNED_INTERFACE(typeArray, ...) TEMPLATE_IF_UNSIGNED(ALL_BUT_FIRST_ARG typeArray) INTERFACE_CLASS(FIRST_ARG typeArray, __VA_ARGS__)

#define INTEGRAL_INTERFACE(typeArray, ...) TEMPLATE_IF_INTEGRAL(ALL_BUT_FIRST_ARG typeArray) INTERFACE_CLASS(FIRST_ARG typeArray, __VA_ARGS__)
#define SIGNED_INTEGRAL_INTERFACE(typeArray, ...) TEMPLATE_IF_SIGNED_INTEGRAL(ALL_BUT_FIRST_ARG typeArray) INTERFACE_CLASS(FIRST_ARG typeArray, __VA_ARGS__)
#define UNSIGNED_INTEGRAL_INTERFACE(typeArray, ...) TEMPLATE_IF_UNSIGNED_INTEGRAL(ALL_BUT_FIRST_ARG typeArray) INTERFACE_CLASS(FIRST_ARG typeArray, __VA_ARGS__)

#define FLOAT_INTERFACE(typeArray, ...) TEMPLATE_IF_FLOAT(ALL_BUT_FIRST_ARG typeArray) INTERFACE_CLASS(FIRST_ARG typeArray, __VA_ARGS__)
#define ENUM_INTERFACE(typeArray, ...) TEMPLATE_IF_ENUM(ALL_BUT_FIRST_ARG typeArray) INTERFACE_CLASS(FIRST_ARG typeArray, __VA_ARGS__)

#endif WINCOPIES_TEMPLATES_INTERFACE_HXX