#pragma once

#ifndef WINCOPIES_TEMPLATES_STRUCT_H
#define WINCOPIES_TEMPLATES_STRUCT_H

#define SIGNED_STRUCT(...) TEMPLATE_IF_SIGNED(__VA_ARGS__) STRUCT
#define UNSIGNED_STRUCT(...) TEMPLATE_IF_UNSIGNED(__VA_ARGS__) STRUCT

#define INTEGRAL_STRUCT(...) TEMPLATE_IF_INTEGRAL(__VA_ARGS__) STRUCT
#define SIGNED_INTEGRAL_STRUCT(...) TEMPLATE_IF_SIGNED_INTEGRAL(__VA_ARGS__) STRUCT
#define UNSIGNED_INTEGRAL_STRUCT(...) TEMPLATE_IF_UNSIGNED_INTEGRAL(__VA_ARGS__) STRUCT

#define FLOAT_STRUCT(...) TEMPLATE_IF_FLOAT(__VA_ARGS__) STRUCT
#define ENUM_STRUCT(...) TEMPLATE_IF_ENUM(__VA_ARGS__) STRUCT

#endif WINCOPIES_TEMPLATES_STRUCT_H