#pragma once

#ifndef WINCOPIES_UTIL_TEMPLATES_CLASS_H
#define WINCOPIES_UTIL_TEMPLATES_CLASS_H

#define SIGNED_CLASS TEMPLATE_IF_SIGNED CLASS
#define UNSIGNED_CLASS TEMPLATE_IF_UNSIGNED CLASS

#define INTEGRAL_CLASS TEMPLATE_IF_INTEGRAL CLASS
#define SIGNED_INTEGRAL_CLASS TEMPLATE_IF_SIGNED_INTEGRAL CLASS
#define UNSIGNED_INTEGRAL_CLASS TEMPLATE_IF_UNSIGNED_INTEGRAL CLASS

#define FLOAT_CLASS TEMPLATE_IF_FLOAT CLASS
#define ENUM_CLASS TEMPLATE_IF_ENUM CLASS



#define MULTI_SIGNED_CLASS(...) MULTI_TEMPLATE_IF_SIGNED(__VA_ARGS__) CLASS
#define MULTI_UNSIGNED_CLASS(...) MULTI_TEMPLATE_IF_UNSIGNED(__VA_ARGS__) CLASS

#define MULTI_INTEGRAL_CLASS(...) MULTI_TEMPLATE_IF_INTEGRAL(__VA_ARGS__) CLASS
#define MULTI_SIGNED_INTEGRAL_CLASS(...) MULTI_TEMPLATE_IF_SIGNED_INTEGRAL(__VA_ARGS__) CLASS
#define MULTI_UNSIGNED_INTEGRAL_CLASS(...) MULTI_TEMPLATE_IF_UNSIGNED_INTEGRAL(__VA_ARGS__) CLASS

#define MULTI_FLOAT_CLASS(...) MULTI_TEMPLATE_IF_FLOAT(__VA_ARGS__) CLASS
#define MULTI_ENUM_CLASS(...) MULTI_TEMPLATE_IF_ENUM(__VA_ARGS__) CLASS

#endif