#pragma once

#ifndef WINCOPIES_UTIL_TEMPLATES_ENUM_H
#define WINCOPIES_UTIL_TEMPLATES_ENUM_H

#define SIGNED_ENUM TEMPLATE_IF_SIGNED ENUM
#define UNSIGNED_ENUM TEMPLATE_IF_UNSIGNED ENUM

#define INTEGRAL_ENUM TEMPLATE_IF_INTEGRAL ENUM
#define SIGNED_INTEGRAL_ENUM TEMPLATE_IF_SIGNED_INTEGRAL ENUM
#define UNSIGNED_INTEGRAL_ENUM TEMPLATE_IF_UNSIGNED_INTEGRAL ENUM

#define FLOAT_ENUM TEMPLATE_IF_FLOAT ENUM
#define ENUM_ENUM TEMPLATE_IF_ENUM ENUM



#define MULTI_SIGNED_ENUM(...) MULTI_TEMPLATE_IF_SIGNED(__VA_ARGS__) ENUM
#define MULTI_UNSIGNED_ENUM(...) MULTI_TEMPLATE_IF_UNSIGNED(__VA_ARGS__) ENUM

#define MULTI_INTEGRAL_ENUM(...) MULTI_TEMPLATE_IF_INTEGRAL(__VA_ARGS__) ENUM
#define MULTI_SIGNED_INTEGRAL_ENUM(...) MULTI_TEMPLATE_IF_SIGNED_INTEGRAL(__VA_ARGS__) ENUM
#define MULTI_UNSIGNED_INTEGRAL_ENUM(...) MULTI_TEMPLATE_IF_UNSIGNED_INTEGRAL(__VA_ARGS__) ENUM

#define MULTI_FLOAT_ENUM(...) MULTI_TEMPLATE_IF_FLOAT(__VA_ARGS__) ENUM
#define MULTI_ENUM_ENUM(...) MULTI_TEMPLATE_IF_ENUM(__VA_ARGS__) ENUM

#endif