#pragma once

#ifndef WINCOPIES_UTIL_TEMPLATES_INTERFACE_H
#define WINCOPIES_UTIL_TEMPLATES_INTERFACE_H

#define SIGNED_INTERFACE TEMPLATE_IF_SIGNED INTERFACE_CLASS
#define UNSIGNED_INTERFACE TEMPLATE_IF_UNSIGNED INTERFACE_CLASS

#define INTEGRAL_INTERFACE TEMPLATE_IF_INTEGRAL INTERFACE_CLASS
#define SIGNED_INTEGRAL_INTERFACE TEMPLATE_IF_SIGNED_INTEGRAL INTERFACE_CLASS
#define UNSIGNED_INTEGRAL_INTERFACE TEMPLATE_IF_UNSIGNED_INTEGRAL INTERFACE_CLASS

#define FLOAT_INTERFACE TEMPLATE_IF_FLOAT INTERFACE_CLASS
#define ENUM_INTERFACE TEMPLATE_IF_ENUM INTERFACE_CLASS



#define MULTI_SIGNED_INTERFACE(...) MULTI_TEMPLATE_IF_SIGNED(__VA_ARGS__) INTERFACE_CLASS
#define MULTI_UNSIGNED_INTERFACE(...) MULTI_TEMPLATE_IF_UNSIGNED(__VA_ARGS__) INTERFACE_CLASS

#define MULTI_INTEGRAL_INTERFACE(...) MULTI_TEMPLATE_IF_INTEGRAL(__VA_ARGS__) INTERFACE_CLASS
#define MULTI_SIGNED_INTEGRAL_INTERFACE(...) MULTI_TEMPLATE_IF_SIGNED_INTEGRAL(__VA_ARGS__) INTERFACE_CLASS
#define MULTI_UNSIGNED_INTEGRAL_INTERFACE(...) MULTI_TEMPLATE_IF_UNSIGNED_INTEGRAL(__VA_ARGS__) INTERFACE_CLASS

#define MULTI_FLOAT_INTERFACE(...) MULTI_TEMPLATE_IF_FLOAT(__VA_ARGS__) INTERFACE_CLASS
#define MULTI_ENUM_INTERFACE(...) MULTI_TEMPLATE_IF_ENUM(__VA_ARGS__) INTERFACE_CLASS

#endif