#pragma once

#ifndef WINCOPIES_UTIL_TEMPLATES_STRUCT_H
#define WINCOPIES_UTIL_TEMPLATES_STRUCT_H

#define SIGNED_STRUCT TEMPLATE_IF_SIGNED STRUCT
#define UNSIGNED_STRUCT TEMPLATE_IF_UNSIGNED STRUCT

#define INTEGRAL_STRUCT TEMPLATE_IF_INTEGRAL STRUCT
#define SIGNED_INTEGRAL_STRUCT TEMPLATE_IF_SIGNED_INTEGRAL STRUCT
#define UNSIGNED_INTEGRAL_STRUCT TEMPLATE_IF_UNSIGNED_INTEGRAL STRUCT

#define FLOAT_STRUCT TEMPLATE_IF_FLOAT STRUCT
#define ENUM_STRUCT TEMPLATE_IF_ENUM STRUCT



#define MULTI_SIGNED_STRUCT(...) MULTI_TEMPLATE_IF_SIGNED(__VA_ARGS__) STRUCT
#define MULTI_UNSIGNED_STRUCT(...) MULTI_TEMPLATE_IF_UNSIGNED(__VA_ARGS__) STRUCT

#define MULTI_INTEGRAL_STRUCT(...) MULTI_TEMPLATE_IF_INTEGRAL(__VA_ARGS__) STRUCT
#define MULTI_SIGNED_INTEGRAL_STRUCT(...) MULTI_TEMPLATE_IF_SIGNED_INTEGRAL(__VA_ARGS__) STRUCT
#define MULTI_UNSIGNED_INTEGRAL_STRUCT(...) MULTI_TEMPLATE_IF_UNSIGNED_INTEGRAL(__VA_ARGS__) STRUCT

#define MULTI_FLOAT_STRUCT(...) MULTI_TEMPLATE_IF_FLOAT(__VA_ARGS__) STRUCT
#define MULTI_ENUM_STRUCT(...) MULTI_TEMPLATE_IF_ENUM(__VA_ARGS__) STRUCT

#endif