#pragma once

#ifndef WINCOPIES_UTIL_TEMPLATES_TEMPLATE_H
#define WINCOPIES_UTIL_TEMPLATES_TEMPLATE_H

#define SIGNED_TEMPLATE(name, ...) TEMPLATE_INTERFACE(name, TEMPLATE_IF_SIGNED, __VA_ARGS__)
#define UNSIGNED_TEMPLATE(name, ...) TEMPLATE_INTERFACE(name, TEMPLATE_IF_UNSIGNED, __VA_ARGS__)

#define INTEGRAL_TEMPLATE(name, ...) TEMPLATE_INTERFACE(name, TEMPLATE_IF_INTEGRAL, __VA_ARGS__)
#define SIGNED_INTEGRAL_TEMPLATE(name, ...) TEMPLATE_INTERFACE(name, TEMPLATE_IF_SIGNED_INTEGRAL, __VA_ARGS__)
#define UNSIGNED_INTEGRAL_TEMPLATE(name, ...) TEMPLATE_INTERFACE(name, TEMPLATE_IF_UNSIGNED_INTEGRAL, __VA_ARGS__)

#define FLOAT_TEMPLATE(name, ...) TEMPLATE_INTERFACE(name, TEMPLATE_IF_FLOAT, __VA_ARGS__)
#define ENUM_TEMPLATE(name, ...) TEMPLATE_INTERFACE(name, TEMPLATE_IF_ENUM, __VA_ARGS__)

#endif // WINCOPIES_UTIL_TEMPLATES_TEMPLATE_H