#pragma once

#ifndef WINCOPIES_UTIL_TEMPLATES_FUNCTION_H
#define WINCOPIES_UTIL_TEMPLATES_FUNCTION_H

#define SIGNED_FUNCTION TEMPLATE_IF_SIGNED FUNCTION
#define UNSIGNED_FUNCTION TEMPLATE_IF_UNSIGNED FUNCTION

#define INTEGRAL_FUNCTION TEMPLATE_IF_INTEGRAL FUNCTION
#define SIGNED_INTEGRAL_FUNCTION TEMPLATE_IF_SIGNED_INTEGRAL FUNCTION
#define UNSIGNED_INTEGRAL_FUNCTION TEMPLATE_IF_UNSIGNED_INTEGRAL FUNCTION

#define FLOAT_FUNCTION TEMPLATE_IF_FLOAT FUNCTION
#define ENUM_FUNCTION TEMPLATE_IF_ENUM FUNCTION



#define MULTI_SIGNED_FUNCTION(...) MULTI_TEMPLATE_IF_SIGNED(__VA_ARGS__) FUNCTION
#define MULTI_UNSIGNED_FUNCTION(...) MULTI_TEMPLATE_IF_UNSIGNED(__VA_ARGS__) FUNCTION

#define MULTI_INTEGRAL_FUNCTION(...) MULTI_TEMPLATE_IF_INTEGRAL(__VA_ARGS__) FUNCTION
#define MULTI_SIGNED_INTEGRAL_FUNCTION(...) MULTI_TEMPLATE_IF_SIGNED_INTEGRAL(__VA_ARGS__) FUNCTION
#define MULTI_UNSIGNED_INTEGRAL_FUNCTION(...) MULTI_TEMPLATE_IF_UNSIGNED_INTEGRAL(__VA_ARGS__) FUNCTION

#define MULTI_FLOAT_FUNCTION(...) MULTI_TEMPLATE_IF_FLOAT(__VA_ARGS__) FUNCTION
#define MULTI_ENUM_FUNCTION(...) MULTI_TEMPLATE_IF_ENUM(__VA_ARGS__) FUNCTION

#endif