#pragma once

#ifndef WINCOPIES_UTIL_TEMPLATES_METHOD_H
#define WINCOPIES_UTIL_TEMPLATES_METHOD_H

#define SIGNED_METHOD TEMPLATE_IF_SIGNED METHOD
#define UNSIGNED_METHOD TEMPLATE_IF_UNSIGNED METHOD

#define INTEGRAL_METHOD TEMPLATE_IF_INTEGRAL METHOD
#define SIGNED_INTEGRAL_METHOD TEMPLATE_IF_SIGNED_INTEGRAL METHOD
#define UNSIGNED_INTEGRAL_METHOD TEMPLATE_IF_UNSIGNED_INTEGRAL METHOD

#define FLOAT_METHOD TEMPLATE_IF_FLOAT METHOD
#define ENUM_METHOD TEMPLATE_IF_ENUM METHOD



#define MULTI_SIGNED_METHOD(...) MULTI_TEMPLATE_IF_SIGNED(__VA_ARGS__) METHOD
#define MULTI_UNSIGNED_METHOD(...) MULTI_TEMPLATE_IF_UNSIGNED(__VA_ARGS__) METHOD

#define MULTI_INTEGRAL_METHOD(...) MULTI_TEMPLATE_IF_INTEGRAL(__VA_ARGS__) METHOD
#define MULTI_SIGNED_INTEGRAL_METHOD(...) MULTI_TEMPLATE_IF_SIGNED_INTEGRAL(__VA_ARGS__) METHOD
#define MULTI_UNSIGNED_INTEGRAL_METHOD(...) MULTI_TEMPLATE_IF_UNSIGNED_INTEGRAL(__VA_ARGS__) METHOD

#define MULTI_FLOAT_METHOD(...) MULTI_TEMPLATE_IF_FLOAT(__VA_ARGS__) METHOD
#define MULTI_ENUM_METHOD(...) MULTI_TEMPLATE_IF_ENUM(__VA_ARGS__) METHOD

#endif