#pragma once

#ifndef WINCOPIES_UTIL_TEMPLATES_METHOD_H
#define WINCOPIES_UTIL_TEMPLATES_METHOD_H

#define SIGNED_METHOD(...) TEMPLATE_IF_SIGNED(__VA_ARGS__) METHOD
#define UNSIGNED_METHOD(...) TEMPLATE_IF_UNSIGNED(__VA_ARGS__) METHOD

#define INTEGRAL_METHOD(...) TEMPLATE_IF_INTEGRAL(__VA_ARGS__) METHOD
#define SIGNED_INTEGRAL_METHOD(...) TEMPLATE_IF_SIGNED_INTEGRAL(__VA_ARGS__) METHOD
#define UNSIGNED_INTEGRAL_METHOD(...) TEMPLATE_IF_UNSIGNED_INTEGRAL(__VA_ARGS__) METHOD

#define FLOAT_METHOD(...) TEMPLATE_IF_FLOAT(__VA_ARGS__) METHOD
#define ENUM_METHOD(...) TEMPLATE_IF_ENUM(__VA_ARGS__) METHOD

#endif