#ifndef WINCOPIES_COLLECTIONS_GLOBAL_H
#define WINCOPIES_COLLECTIONS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WINCOPIES_COLLECTIONS_LIBRARY)
#  define WINCOPIES_COLLECTIONSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WINCOPIES_COLLECTIONSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WINCOPIES_COLLECTIONS_GLOBAL_H
