#pragma once

#ifndef WINCOPIES_UTIL_ENUM_COMPARISON_HPP
#define WINCOPIES_UTIL_ENUM_COMPARISON_HPP

#include "Operators.hpp"
#include "../Util.h"

ENUM_COMPARISON_OPERATOR(< )
ENUM_COMPARISON_OPERATOR2(< )

ENUM_COMPARISON_OPERATOR(<= )
ENUM_COMPARISON_OPERATOR2(<= )

ENUM_COMPARISON_OPERATOR(> )
ENUM_COMPARISON_OPERATOR2(> )

ENUM_COMPARISON_OPERATOR(>= )
ENUM_COMPARISON_OPERATOR2(>= )

#endif // WINCOPIES_UTIL_ENUM_COMPARISON_HPP