#pragma once

#ifndef WINCOPIES_UTIL_ENUM_COMPARISON_H
#define WINCOPIES_UTIL_ENUM_COMPARISON_H

#include "Operators.h"
#include "../Util.h"

ENUM_COMPARISON_OPERATOR(< )
ENUM_COMPARISON_OPERATOR2(< )

ENUM_COMPARISON_OPERATOR(<= )
ENUM_COMPARISON_OPERATOR2(<= )

ENUM_COMPARISON_OPERATOR(> )
ENUM_COMPARISON_OPERATOR2(> )

ENUM_COMPARISON_OPERATOR(>= )
ENUM_COMPARISON_OPERATOR2(>= )

#endif