#pragma once

#ifndef WINCOPIES_REFLECTION_ENUMS_H
#define WINCOPIES_REFLECTION_ENUMS_H

#define VIRTUALITY_NONE 0
#define VIRTUALITY_ABSTRACT 1
#define VIRTUALITY_OVERRIDE 2
#define VIRTUALITY_FINAL 3

#endif WINCOPIES_REFLECTION_ENUMS_H